//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.18408.
// 
#pragma warning disable 1591

namespace CinemaCRM.SendSMS.vn.brandsms {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="VMGAPISoap", Namespace="http://tempuri.org/")]
    public partial class VMGAPI : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback AdsSendSmsOperationCompleted;
        
        private System.Threading.SendOrPostCallback AdsGPCSendSmsOperationCompleted;
        
        private System.Threading.SendOrPostCallback BulkSendSmsOperationCompleted;
        
        private System.Threading.SendOrPostCallback BulkSendSmsWithRequestIdOperationCompleted;
        
        private System.Threading.SendOrPostCallback BulkMessageBlockReciverOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public VMGAPI() {
            this.Url = global::CinemaCRM.SendSMS.Properties.Settings.Default.CinemaCRM_SendSMS_vn_brandsms_VMGAPI;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event AdsSendSmsCompletedEventHandler AdsSendSmsCompleted;
        
        /// <remarks/>
        public event AdsGPCSendSmsCompletedEventHandler AdsGPCSendSmsCompleted;
        
        /// <remarks/>
        public event BulkSendSmsCompletedEventHandler BulkSendSmsCompleted;
        
        /// <remarks/>
        public event BulkSendSmsWithRequestIdCompletedEventHandler BulkSendSmsWithRequestIdCompleted;
        
        /// <remarks/>
        public event BulkMessageBlockReciverCompletedEventHandler BulkMessageBlockReciverCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AdsSendSms", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ApiAdsReturn AdsSendSms(string[] msisdns, string alias, string message, string sendTime, string authenticateUser, string authenticatePass) {
            object[] results = this.Invoke("AdsSendSms", new object[] {
                        msisdns,
                        alias,
                        message,
                        sendTime,
                        authenticateUser,
                        authenticatePass});
            return ((ApiAdsReturn)(results[0]));
        }
        
        /// <remarks/>
        public void AdsSendSmsAsync(string[] msisdns, string alias, string message, string sendTime, string authenticateUser, string authenticatePass) {
            this.AdsSendSmsAsync(msisdns, alias, message, sendTime, authenticateUser, authenticatePass, null);
        }
        
        /// <remarks/>
        public void AdsSendSmsAsync(string[] msisdns, string alias, string message, string sendTime, string authenticateUser, string authenticatePass, object userState) {
            if ((this.AdsSendSmsOperationCompleted == null)) {
                this.AdsSendSmsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAdsSendSmsOperationCompleted);
            }
            this.InvokeAsync("AdsSendSms", new object[] {
                        msisdns,
                        alias,
                        message,
                        sendTime,
                        authenticateUser,
                        authenticatePass}, this.AdsSendSmsOperationCompleted, userState);
        }
        
        private void OnAdsSendSmsOperationCompleted(object arg) {
            if ((this.AdsSendSmsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AdsSendSmsCompleted(this, new AdsSendSmsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AdsGPCSendSms", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ApiBulkReturn AdsGPCSendSms(string msisdn, string alias, string message, string sendTime, string authenticateUser, string authenticatePass) {
            object[] results = this.Invoke("AdsGPCSendSms", new object[] {
                        msisdn,
                        alias,
                        message,
                        sendTime,
                        authenticateUser,
                        authenticatePass});
            return ((ApiBulkReturn)(results[0]));
        }
        
        /// <remarks/>
        public void AdsGPCSendSmsAsync(string msisdn, string alias, string message, string sendTime, string authenticateUser, string authenticatePass) {
            this.AdsGPCSendSmsAsync(msisdn, alias, message, sendTime, authenticateUser, authenticatePass, null);
        }
        
        /// <remarks/>
        public void AdsGPCSendSmsAsync(string msisdn, string alias, string message, string sendTime, string authenticateUser, string authenticatePass, object userState) {
            if ((this.AdsGPCSendSmsOperationCompleted == null)) {
                this.AdsGPCSendSmsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAdsGPCSendSmsOperationCompleted);
            }
            this.InvokeAsync("AdsGPCSendSms", new object[] {
                        msisdn,
                        alias,
                        message,
                        sendTime,
                        authenticateUser,
                        authenticatePass}, this.AdsGPCSendSmsOperationCompleted, userState);
        }
        
        private void OnAdsGPCSendSmsOperationCompleted(object arg) {
            if ((this.AdsGPCSendSmsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AdsGPCSendSmsCompleted(this, new AdsGPCSendSmsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/BulkSendSms", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ApiBulkReturn BulkSendSms(string msisdn, string alias, string message, string sendTime, string authenticateUser, string authenticatePass) {
            object[] results = this.Invoke("BulkSendSms", new object[] {
                        msisdn,
                        alias,
                        message,
                        sendTime,
                        authenticateUser,
                        authenticatePass});
            return ((ApiBulkReturn)(results[0]));
        }
        
        /// <remarks/>
        public void BulkSendSmsAsync(string msisdn, string alias, string message, string sendTime, string authenticateUser, string authenticatePass) {
            this.BulkSendSmsAsync(msisdn, alias, message, sendTime, authenticateUser, authenticatePass, null);
        }
        
        /// <remarks/>
        public void BulkSendSmsAsync(string msisdn, string alias, string message, string sendTime, string authenticateUser, string authenticatePass, object userState) {
            if ((this.BulkSendSmsOperationCompleted == null)) {
                this.BulkSendSmsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnBulkSendSmsOperationCompleted);
            }
            this.InvokeAsync("BulkSendSms", new object[] {
                        msisdn,
                        alias,
                        message,
                        sendTime,
                        authenticateUser,
                        authenticatePass}, this.BulkSendSmsOperationCompleted, userState);
        }
        
        private void OnBulkSendSmsOperationCompleted(object arg) {
            if ((this.BulkSendSmsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.BulkSendSmsCompleted(this, new BulkSendSmsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/BulkSendSmsWithRequestId", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ApiBulkReturn BulkSendSmsWithRequestId(string requestId, string msisdn, string alias, string message, string sendTime, string authenticateUser, string authenticatePass) {
            object[] results = this.Invoke("BulkSendSmsWithRequestId", new object[] {
                        requestId,
                        msisdn,
                        alias,
                        message,
                        sendTime,
                        authenticateUser,
                        authenticatePass});
            return ((ApiBulkReturn)(results[0]));
        }
        
        /// <remarks/>
        public void BulkSendSmsWithRequestIdAsync(string requestId, string msisdn, string alias, string message, string sendTime, string authenticateUser, string authenticatePass) {
            this.BulkSendSmsWithRequestIdAsync(requestId, msisdn, alias, message, sendTime, authenticateUser, authenticatePass, null);
        }
        
        /// <remarks/>
        public void BulkSendSmsWithRequestIdAsync(string requestId, string msisdn, string alias, string message, string sendTime, string authenticateUser, string authenticatePass, object userState) {
            if ((this.BulkSendSmsWithRequestIdOperationCompleted == null)) {
                this.BulkSendSmsWithRequestIdOperationCompleted = new System.Threading.SendOrPostCallback(this.OnBulkSendSmsWithRequestIdOperationCompleted);
            }
            this.InvokeAsync("BulkSendSmsWithRequestId", new object[] {
                        requestId,
                        msisdn,
                        alias,
                        message,
                        sendTime,
                        authenticateUser,
                        authenticatePass}, this.BulkSendSmsWithRequestIdOperationCompleted, userState);
        }
        
        private void OnBulkSendSmsWithRequestIdOperationCompleted(object arg) {
            if ((this.BulkSendSmsWithRequestIdCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.BulkSendSmsWithRequestIdCompleted(this, new BulkSendSmsWithRequestIdCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/BulkMessageBlockReciver", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ApiBulkBlockReturn BulkMessageBlockReciver(string[] msisdns, string alias, string message, string sendTime, string authenticateUser, string authenticatePass) {
            object[] results = this.Invoke("BulkMessageBlockReciver", new object[] {
                        msisdns,
                        alias,
                        message,
                        sendTime,
                        authenticateUser,
                        authenticatePass});
            return ((ApiBulkBlockReturn)(results[0]));
        }
        
        /// <remarks/>
        public void BulkMessageBlockReciverAsync(string[] msisdns, string alias, string message, string sendTime, string authenticateUser, string authenticatePass) {
            this.BulkMessageBlockReciverAsync(msisdns, alias, message, sendTime, authenticateUser, authenticatePass, null);
        }
        
        /// <remarks/>
        public void BulkMessageBlockReciverAsync(string[] msisdns, string alias, string message, string sendTime, string authenticateUser, string authenticatePass, object userState) {
            if ((this.BulkMessageBlockReciverOperationCompleted == null)) {
                this.BulkMessageBlockReciverOperationCompleted = new System.Threading.SendOrPostCallback(this.OnBulkMessageBlockReciverOperationCompleted);
            }
            this.InvokeAsync("BulkMessageBlockReciver", new object[] {
                        msisdns,
                        alias,
                        message,
                        sendTime,
                        authenticateUser,
                        authenticatePass}, this.BulkMessageBlockReciverOperationCompleted, userState);
        }
        
        private void OnBulkMessageBlockReciverOperationCompleted(object arg) {
            if ((this.BulkMessageBlockReciverCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.BulkMessageBlockReciverCompleted(this, new BulkMessageBlockReciverCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ApiAdsReturn {
        
        private int error_codeField;
        
        private string error_detailField;
        
        private string prog_codeField;
        
        private APIAdsSendMT[] detailField;
        
        /// <remarks/>
        public int error_code {
            get {
                return this.error_codeField;
            }
            set {
                this.error_codeField = value;
            }
        }
        
        /// <remarks/>
        public string error_detail {
            get {
                return this.error_detailField;
            }
            set {
                this.error_detailField = value;
            }
        }
        
        /// <remarks/>
        public string prog_code {
            get {
                return this.prog_codeField;
            }
            set {
                this.prog_codeField = value;
            }
        }
        
        /// <remarks/>
        public APIAdsSendMT[] detail {
            get {
                return this.detailField;
            }
            set {
                this.detailField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class APIAdsSendMT {
        
        private string telcoField;
        
        private int error_codeField;
        
        private string error_detailField;
        
        private string prog_codeField;
        
        private int total_subField;
        
        private int total_smsField;
        
        /// <remarks/>
        public string telco {
            get {
                return this.telcoField;
            }
            set {
                this.telcoField = value;
            }
        }
        
        /// <remarks/>
        public int error_code {
            get {
                return this.error_codeField;
            }
            set {
                this.error_codeField = value;
            }
        }
        
        /// <remarks/>
        public string error_detail {
            get {
                return this.error_detailField;
            }
            set {
                this.error_detailField = value;
            }
        }
        
        /// <remarks/>
        public string prog_code {
            get {
                return this.prog_codeField;
            }
            set {
                this.prog_codeField = value;
            }
        }
        
        /// <remarks/>
        public int total_sub {
            get {
                return this.total_subField;
            }
            set {
                this.total_subField = value;
            }
        }
        
        /// <remarks/>
        public int total_sms {
            get {
                return this.total_smsField;
            }
            set {
                this.total_smsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class msisdnInfo {
        
        private string msisdnField;
        
        private int isSuccessField;
        
        private string msgField;
        
        private string messageidField;
        
        /// <remarks/>
        public string msisdn {
            get {
                return this.msisdnField;
            }
            set {
                this.msisdnField = value;
            }
        }
        
        /// <remarks/>
        public int isSuccess {
            get {
                return this.isSuccessField;
            }
            set {
                this.isSuccessField = value;
            }
        }
        
        /// <remarks/>
        public string msg {
            get {
                return this.msgField;
            }
            set {
                this.msgField = value;
            }
        }
        
        /// <remarks/>
        public string messageid {
            get {
                return this.messageidField;
            }
            set {
                this.messageidField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ApiBulkBlockReturn {
        
        private int error_codeField;
        
        private string error_detailField;
        
        private string progCodeField;
        
        private string blackListField;
        
        private int doublicNumbersField;
        
        private int wrongNumbersField;
        
        private msisdnInfo[] detailField;
        
        /// <remarks/>
        public int error_code {
            get {
                return this.error_codeField;
            }
            set {
                this.error_codeField = value;
            }
        }
        
        /// <remarks/>
        public string error_detail {
            get {
                return this.error_detailField;
            }
            set {
                this.error_detailField = value;
            }
        }
        
        /// <remarks/>
        public string progCode {
            get {
                return this.progCodeField;
            }
            set {
                this.progCodeField = value;
            }
        }
        
        /// <remarks/>
        public string blackList {
            get {
                return this.blackListField;
            }
            set {
                this.blackListField = value;
            }
        }
        
        /// <remarks/>
        public int doublicNumbers {
            get {
                return this.doublicNumbersField;
            }
            set {
                this.doublicNumbersField = value;
            }
        }
        
        /// <remarks/>
        public int wrongNumbers {
            get {
                return this.wrongNumbersField;
            }
            set {
                this.wrongNumbersField = value;
            }
        }
        
        /// <remarks/>
        public msisdnInfo[] detail {
            get {
                return this.detailField;
            }
            set {
                this.detailField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ApiBulkReturn {
        
        private int error_codeField;
        
        private string error_detailField;
        
        private int messageIdField;
        
        /// <remarks/>
        public int error_code {
            get {
                return this.error_codeField;
            }
            set {
                this.error_codeField = value;
            }
        }
        
        /// <remarks/>
        public string error_detail {
            get {
                return this.error_detailField;
            }
            set {
                this.error_detailField = value;
            }
        }
        
        /// <remarks/>
        public int messageId {
            get {
                return this.messageIdField;
            }
            set {
                this.messageIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void AdsSendSmsCompletedEventHandler(object sender, AdsSendSmsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AdsSendSmsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AdsSendSmsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ApiAdsReturn Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ApiAdsReturn)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void AdsGPCSendSmsCompletedEventHandler(object sender, AdsGPCSendSmsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AdsGPCSendSmsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AdsGPCSendSmsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ApiBulkReturn Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ApiBulkReturn)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void BulkSendSmsCompletedEventHandler(object sender, BulkSendSmsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class BulkSendSmsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal BulkSendSmsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ApiBulkReturn Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ApiBulkReturn)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void BulkSendSmsWithRequestIdCompletedEventHandler(object sender, BulkSendSmsWithRequestIdCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class BulkSendSmsWithRequestIdCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal BulkSendSmsWithRequestIdCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ApiBulkReturn Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ApiBulkReturn)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void BulkMessageBlockReciverCompletedEventHandler(object sender, BulkMessageBlockReciverCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class BulkMessageBlockReciverCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal BulkMessageBlockReciverCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ApiBulkBlockReturn Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ApiBulkBlockReturn)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591